@startuml streetcats
class Cat {
    + id: int
    + userid: integer
    + title: varchar
    + description: text
    + photo_url: varchar
    + latitude: float
    + longitude: float
    + created_at: datetime
}


class User {
    + id: int 
    + username: varchar
    + email: varchar
    + password: varchar

}


class Comment {
    + id: int
    + catid: int
    + userid: int
    + testo: varchar
    + data: datetime
}

Cat ---> User : avvistato_da
User --> Comment : scrive
Comment --> Cat : commenta_su
@enduml